// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignuptestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signuppage1() {
    // Test name: Sign up page 1
    // Step # | name | target | value | comment
    // 1 | open | https://thinking-tester-contact-list.herokuapp.com/addUser |  | 
    driver.get("https://thinking-tester-contact-list.herokuapp.com/addUser");
    // 2 | setWindowSize | 784x818 |  | 
    driver.manage().window().setSize(new Dimension(784, 818));
    // 3 | click | id=firstName |  | 
    driver.findElement(By.id("firstName")).click();
    // 4 | type | id=firstName | Mashrur | 
    driver.findElement(By.id("firstName")).sendKeys("Mashrur");
    // 5 | click | id=lastName |  | 
    driver.findElement(By.id("lastName")).click();
    // 6 | type | id=lastName | Ahsan | 
    driver.findElement(By.id("lastName")).sendKeys("Ahsan");
    // 7 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 8 | type | id=email | mak_115 | 
    driver.findElement(By.id("email")).sendKeys("mak_115");
    // 9 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 10 | type | id=password | 1234567 | 
    driver.findElement(By.id("password")).sendKeys("1234567");
    // 11 | click | id=submit |  | 
    driver.findElement(By.id("submit")).click();
  }
  @Test
  public void signuppage2() {
    // Test name: Sign up page 2
    // Step # | name | target | value | comment
    // 1 | open | https://thinking-tester-contact-list.herokuapp.com/addUser |  | 
    driver.get("https://thinking-tester-contact-list.herokuapp.com/addUser");
    // 2 | setWindowSize | 784x816 |  | 
    driver.manage().window().setSize(new Dimension(784, 816));
    // 3 | click | id=firstName |  | 
    driver.findElement(By.id("firstName")).click();
    // 4 | type | id=firstName | Mashrur | 
    driver.findElement(By.id("firstName")).sendKeys("Mashrur");
    // 5 | click | id=lastName |  | 
    driver.findElement(By.id("lastName")).click();
    // 6 | type | id=lastName | Ahsan | 
    driver.findElement(By.id("lastName")).sendKeys("Ahsan");
    // 7 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 8 | type | id=email | mak.115@user.com | 
    driver.findElement(By.id("email")).sendKeys("mak.115@user.com");
    // 9 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 10 | click | css=html |  | 
    driver.findElement(By.cssSelector("html")).click();
    // 11 | type | id=password | 12345 | 
    driver.findElement(By.id("password")).sendKeys("12345");
    // 12 | click | id=submit |  | 
    driver.findElement(By.id("submit")).click();
  }
  @Test
  public void signuppage3() {
    // Test name: Sign up page 3
    // Step # | name | target | value | comment
    // 1 | open | https://thinking-tester-contact-list.herokuapp.com/addUser |  | 
    driver.get("https://thinking-tester-contact-list.herokuapp.com/addUser");
    // 2 | setWindowSize | 785x817 |  | 
    driver.manage().window().setSize(new Dimension(785, 817));
    // 3 | click | id=firstName |  | 
    driver.findElement(By.id("firstName")).click();
    // 4 | type | id=firstName | Mashrur | 
    driver.findElement(By.id("firstName")).sendKeys("Mashrur");
    // 5 | click | id=add-user |  | 
    driver.findElement(By.id("add-user")).click();
    // 6 | click | id=lastName |  | 
    driver.findElement(By.id("lastName")).click();
    // 7 | type | id=lastName | Ahsan | 
    driver.findElement(By.id("lastName")).sendKeys("Ahsan");
    // 8 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 9 | type | id=email | mak.115@user.com | 
    driver.findElement(By.id("email")).sendKeys("mak.115@user.com");
    // 10 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 11 | type | id=password | 1234567 | 
    driver.findElement(By.id("password")).sendKeys("1234567");
    // 12 | click | id=submit |  | 
    driver.findElement(By.id("submit")).click();
    // 13 | click | css=.main-content |  | 
    driver.findElement(By.cssSelector(".main-content")).click();
    // 14 | click | css=.main-content |  | 
    driver.findElement(By.cssSelector(".main-content")).click();
  }
}
