// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomePageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void homePageSortAtoZ() {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1235, 749));
    driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Name (A - Z)']")).click();
    }
  }


  @Test
  public void homePageFilterBrand1() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1242, 754));
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(19) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(18) > label")).click();
    js.executeScript("window.scrollTo(0,280.79998779296875)");
    Thread.sleep(2000);
    driver.findElement(By.linkText("»")).click();
    driver.findElement(By.linkText("»")).click();
    driver.findElement(By.linkText("5")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(19) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.linkText("4")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".disabled")).click();
    Thread.sleep(2000);
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.linkText("1")).click();
  }

  @Test
  public void homePageFilterBrand2() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1246, 758));
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(18) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.id("filters")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(19) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(18) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(19) > label")).click();
    Thread.sleep(2000);
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".checkbox:nth-child(19) > label")).click();
  }

  @Test
  public void homePageFilterCategory1() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1242, 754));
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(13) > label")).click();
    Thread.sleep(3000);
  }

  @Test
  public void homePageFilterCategory2() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1242, 754));
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) > label")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) .checkbox:nth-child(1) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) .checkbox:nth-child(1) > label")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) .checkbox:nth-child(3) > label")).click();
    Thread.sleep(2000);
  }

  @Test
  public void homePageFilterCategory3() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1242, 754));
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(1) > label")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(4) > label")).click();
    js.executeScript("window.scrollTo(0,303.20001220703125)");
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(13) .checkbox:nth-child(4) > label")).click();
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(13) .checkbox:nth-child(1) > label")).click();
    Thread.sleep(3000);
    driver.findElement(By.linkText("2")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(15) .checkbox:nth-child(3) > label")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) .checkbox:nth-child(2) > label")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) .checkbox:nth-child(3) > label")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".checkbox:nth-child(14) .checkbox:nth-child(4) > label")).click();
    Thread.sleep(3000);
    driver.findElement(By.linkText("3")).click();
    Thread.sleep(3000);
  }

  @Test
  public void homePagePriceRange() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1242, 754));
    {
      WebElement element = driver.findElement(By.id("filters"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("filters"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("filters"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("filters")).click();
    driver.findElement(By.cssSelector(".ngx-slider-selection-bar")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ngx-slider-pointer-min")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ngx-slider-pointer-min")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ngx-slider-pointer-max")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-min"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ngx-slider-pointer-min")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ngx-slider-pointer-max"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".ngx-slider-pointer-max")).click();
  }

  @Test
  public void homePageSearchBar() throws InterruptedException {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1250, 762));
    js.executeScript("window.scrollTo(0,390.3999938964844)");
    Thread.sleep(3000);
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Thor");
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys(Keys.ENTER);
    Thread.sleep(3000);
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("DRill");
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("BENCH");
    Thread.sleep(3000);
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-reset\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    Thread.sleep(3000);
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("BUnch");
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"search-reset\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"search-query\"]")).sendKeys("Screw");
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"search-submit\"]")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"search-reset\"]")).click();
  }

  @Test
  public void homePageSortZtoA() {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1242, 754));
    js.executeScript("window.scrollTo(0,28)");
    driver.findElement(By.cssSelector("*[data-test=\"sort\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"sort\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Name (Z - A)']")).click();
    }
  }
}
